// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADAvMccNCucO5WhNuGcBFgoxeap8Z8Alk',
    appId: '1:872937595912:web:44fd27a41d5191c72bddbd',
    messagingSenderId: '872937595912',
    projectId: 'travel-hub-87ef6',
    authDomain: 'travel-hub-87ef6.firebaseapp.com',
    storageBucket: 'travel-hub-87ef6.firebasestorage.app',
    measurementId: 'G-GY7X1BDRF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGf7gi7oH45Q1kuRlTAid8pWjw7kNQgik',
    appId: '1:872937595912:android:d363f23ef62491e92bddbd',
    messagingSenderId: '872937595912',
    projectId: 'travel-hub-87ef6',
    storageBucket: 'travel-hub-87ef6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy0WGaOTi7J0aXNEw4DLNGX6IHEyjNtyw',
    appId: '1:872937595912:ios:b678f92b92918bae2bddbd',
    messagingSenderId: '872937595912',
    projectId: 'travel-hub-87ef6',
    storageBucket: 'travel-hub-87ef6.firebasestorage.app',
    androidClientId: '872937595912-7a5vtiqf88tsgtp2dl38g4btd22prqjk.apps.googleusercontent.com',
    iosClientId: '872937595912-tgs0at6315k4u6kedv47feq6k52lcdr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelHub',
  );
}
